language: python
python:
- 3.4
- 3.5
- 3.6
- 3.7
dist: trusty
matrix:
  include:
    - os: windows
      language: sh
      before_install:
        # this hackery is in here because of https://github.com/git-for-windows/git/issues/2291
        - powershell mkdir "'C:\Program Files\Git\dev'"
        - ln -s /proc/self/fd /dev/fd
        - choco install make
        - choco install python
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python -m pip install python-magic-win64
install:
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip freeze
script:
  - set -eo pipefail
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
